name: Docker

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        env:
          - SCRIPT: docker_images

    env: ${{ matrix.env }}
    timeout-minutes: 70
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Docker images
        run: |
          bash -x "./examples/${SCRIPT}.sh"
