name: Ubuntu 20.04 (latest)

on:
  pull_request:
  push:
    branches:
      - master
      - 'release/**'

env:
  # For tzdata interactive input during apt-get install
  DEBIAN_FRONTEND: noninteractive

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    container:
      image: ubuntu:20.04
    strategy:
      matrix:
        env:
          - SCRIPT: all_latest

    env: ${{ matrix.env }}
    timeout-minutes: 70
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up build environment
        run: |
          SUDO=
          ! command -v sudo >/dev/null || SUDO=sudo
          $SUDO apt-get update
          $SUDO apt-get -y install \
            sudo \
            git \
            autoconf automake libtool bison \
            libncurses5-dev libncursesw5-dev libbz2-dev libz-dev \
            libgnutls28-dev bzip2 make gettext texinfo gnutls-bin build-essential g++
      - name: Build GPG
        run: |
          bash -x "./examples/${SCRIPT}.sh"
